# netlify.toml

[build]
  command = "solid-start build"
  functions = "netlify/functions"
  publish = "netlify"

[[redirects]]
  from = "/*"
  to = "https://www.airtable.com/:splat"
  status = 301
  force = true
