# netlify.toml

[build]
  command = "solid-start build"
  functions = "netlify/functions"
  publish = "netlify"

[[redirects]]
  from = "https://dialflow.mosping.com/clearcover"
  to = "https://airtable.com/app3q4iLUHKT4SPCk/pag5sCOF2bDusahsv"
  status = 200

