# netlify.toml

[build]
  command = "solid-start build"
  functions = "netlify/functions"
  publish = "netlify"

[[redirects]]
  from = "https://clearcover.ucmesh.com"
  to = "https://airtable.com"
  status = 301
  force = true
